### ISSUE TITLE
Pull time entries and current activity

### ISSUE THREAD

**Issue by kkawatra09** [MattParr/python-atws#36]
Hello,

Can we see the activity on a ticket? Right now the query is just pulling the basic information about the ticket but if we want to see how much work is done or is there any conversation on the ticket or time entries, etc.

Please let me know
Thank you

**Comment by MattParr** [comment]
sure.  you could do something like:
```python
def get_tickets_with_notes(at, tickets):
  for ticket in tickets:
    query = Query('TicketNote')
    query.WHERE('TicketID', query.Equals, ticket.id)
    ticket_notes = at.query(query)
    yield ticket, ticket_notes

tickets = at.query(query)
tickets_with_notes = get_tickets_with_notes(at, tickets)
for ticket,ticket_notes in tickets_with_notes:
  print(ticket)
  print('********')
  for ticket_note in ticket_notes:
    print(ticket_note)
```

**Comment by kkawatra09** [comment]
Great, thanks
I tried something similar yesterday and it worked out. Thank you for your
response though.
I do have one more question if you don't mind me asking. I an having hard
time adding a Description, while creating ticket. Looks like Description is
not an attribute. I tried using User Defined Field but no luck. Is there a
way we can add a Description while creating ticket?
Hope to hear back from you soon.

Thank you,
Kay

**Comment by MattParr** [comment]
I'm not aware of any problems creating a ticket using something like 
https://atws.readthedocs.io/usage.html#creating-entities along with:

```python
ticket.Description = 'this is a description.  it has an 8000 character limit, including whitespace and control characters'

```
