### ISSUE TITLE
Sorry but this autotask soap wrapper is a total mess....

### ISSUE THREAD

**Issue by evoportals** [MattParr/python-atws#39]
create_picklist_module does not work, documentation is servery lacking. Tons of errors.

**Comment by MattParr** [comment]
@evoportals Thanks for the feedback.
I agree on every point.
I've removed the picklist module from the next release.  I don't use it, and it seems to be a problem for most people who come across this project.

Other than the picklist module, I'd really appreciate if you took the time to create an issue for other errors.

In what areas could I improve the documentation?
