### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by cstoltze** [MattParr/python-atws#41]
Thank you for spending the time and effort to develop this project.

I would like to be able to create and access autotask ticket attachments using atws. Is this currently possible?

Trying to execute the following:

```
query = atws.Query('Attachment')
query.WHERE('id', query.GreaterThan, 0)
attachment = at.query(query).fetch_one()
```

gave the following error.

```
'Autotask API has returned an error.
Please process the response attribute in this exception to detirmine 
 the extent of this failure.
 '[Unable to cast object of type 'autotask.web.services.API.Attachment' to type 'autotask.web.services.API.ExternalVbApiEntity'., '<queryxml
><entity>Attachment</entity><query><field>id<expression op="GreaterThan">0</expression></field></query></queryxml>']
```

**Comment by MattParr** [comment]
I don't think Attachment is an entity type that they allow you to get.  That error message sure is an interesting disclosure from their webservice though.

AttachmentInfo is all we can query.
The API specifies other specific calls relating to Attachment API Calls.  The last thing they want to you to be able to do is download 500 attachments at a time.

I'm sorry it took me so long to get to this message but hope the above helps.  I'll be doing some attachment work this week, so I may get a chance to create an example for them in the docs.
