### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by mcl12345** [MattParr/python-atws#43]
**When I do :**
query = atws.Query('Account')
query.WHERE('id', query.GreaterThan, 0)
query.Bracket('AND')
query.OR('Status',      query.Equals,   at.picklist['Ticket']['Status']['Complete'])
query.OR('IssueType',   query.Equals,   at.picklist['Ticket']['IssueType']['Non Work Issues'])
query.CloseBracket()

**I have this error :**
Traceback (most recent call last):
  File "test2.py", line 36, in <module>
    query.Bracket('AND')
AttributeError: 'Query' object has no attribute 'Bracket'

**Someone can help ?**

**Comment by MattParr** [comment]
python-atws/atws/query.py was refactored some time ago in commit 7761fb3ac128ddb8c7c2dcad972b6a43f07e7b4b and since then, the documentation has been wrong.  I've fixed up the documentation.

**Comment by mcl12345** [comment]
**So it's :**
query.open_bracket('AND') ?

The documentation didn't change :
https://atws.readthedocs.io/usage.html#querying-for-entities

**Comment by MattParr** [comment]
The documentation did change I think you just need to refresh.

Regardless, yes that is the correct method to call open_bracket('AND')

**Comment by mcl12345** [comment]
Ok, yes I needed to delete cache in the browser.
