### ISSUE TITLE
Create Entity error

### ISSUE THREAD

**Issue by mcl12345** [MattParr/python-atws#44]
**When I try to create an entity Ticket , I have this error :**

Traceback (most recent call last):
  File "test2.py", line 66, in <module>
    ticket.Priority = at.picklist['Ticket']['Priority']['Standard']
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 240, in __getitem__
    return self.lookup(item)
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 219, in lookup
    return get_label_value(label, self._picklist)
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 55, in get_label_value
    item = find('Label', label, picklistvalues, condition=condition)
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 34, in find
    raise KeyError('label not found in index', index_label, index_name)
KeyError: ('label not found in index', 'Label', 'Standard')

**with :** 
ticket = at.new('Ticket')
ticket.Title = 'test ticket'
#ticket.AccountID = 0
ticket.DueDateTime = datetime.now()
ticket.Priority = at.picklist['Ticket']['Priority']['Standard']
ticket.Status = at.picklist['Ticket']['Status']['New']
ticket.create() # updates the ticket object inline using CRUD patch

**Someone can help ?**

**Comment by MattParr** [comment]
Autotask includes four basic priorities. Critical, High, Medium, Low.
Are you sure you have a Standard priority?  The error: "label not found in index" means that Standard was not found in the list of priorities.

**Comment by mcl12345** [comment]
**Thanks, it seems to work for "priority"**

**I have a second error :**
Traceback (most recent call last):
  File "test2.py", line 23, in <module>
    ticket.QueueID = at.picklist['Ticket']['QueueID']['Your_Queue_Name_Here']
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 240, in __getitem__
    return self.lookup(item)
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 219, in lookup
    return get_label_value(label, self._picklist)
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 55, in get_label_value
    item = find('Label', label, picklistvalues, condition=condition)
  File "/usr/local/lib/python2.7/dist-packages/atws/picklist.py", line 34, in find
    raise KeyError('label not found in index', index_label, index_name)
KeyError: ('label not found in index', 'Label', 'Your_Queue_Name_Here')

**I have this error with the following code :**
**What can I put for QueueID ?**

import atws
import atws.monkeypatch.attributes
from datetime import datetime

at = atws.connect(username='*****************************',
                  password='*****************************',
                  support_file_path='/tmp')

ticket = at.new('Ticket')
ticket.Title = 'Test ticket - no id yet'
ticket.AccountID = 0
ticket.DueDateTime = datetime.now()
ticket.QueueID = at.picklist['Ticket']['QueueID']['Your_Queue_Name_Here']
ticket.Priority = at.picklist['Ticket']['Priority']['Medium']
ticket.Status = at.picklist['Ticket']['Status']['New']
ticket.create() # this will create the ticket in Autotask

ticket.Title = 'I changed this'
ticket.update() # this will update the ticket in Autotask

**Comment by MattParr** [comment]
Instead of "your_queue_name_here" try putting in the name of a queue

**Comment by mcl12345** [comment]
How can I create a queue ?

**Comment by MattParr** [comment]
You cannot create a queue using the API.  You must do it in the UI.

**Comment by MattParr** [comment]
query.close_bracket()

not

query.CloseBracket()

**Comment by mcl12345** [comment]
It works with :
ticket.QueueID = at.picklist['Ticket']['QueueID']['Level I Support']
