### ISSUE TITLE
How can I create a multi-site ?

### ISSUE THREAD

**Issue by mcl12345** [MattParr/python-atws#50]
Hi,

I have created accounts in Autotask, but How I can create a multi-site where different locations exist with the API ?

I have created locations directly via Autotask website and I did that :

     query = atws.Query('Location')
     query.WHERE('id', query.Equals, "0")

     print query.pretty_print()

     locations = at.query(query)

     # enumerate them
     for location in locations:
          print location

But I had that :
Traceback (most recent call last):
  File "search_locations.py", line 32, in <module>
    for location in locations:
  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 372, in _query
    response.raise_or_return_entities()
  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 137, in raise_or_return_entities
    self._raise()
  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 141, in _raise
    raise AutotaskAPIException(self)
atws.wrapper.AutotaskAPIException: 'Autotask API has returned an error.\n    Please process the response attribute in this exception to detirmine \n    the extent of this failure.\n    '[Value cannot be null.
Parameter name: type, '<queryxml><entity>Location</entity><query><field>id<expression op="Equals">0</expression></field><condition operator="AND" /></query></queryxml>']

How to do to search locations ?

And how do I create location via API ? :

    location = at.new('Location')
    location.LocationName = 'Test account api python 1'
    location.Phone = "0185762128"
    location.Address1        = "une adresse"
    location.BillToAddress1  = "une adresse"
    location.City            = "une ville"
    location.BillToCity      = "une ville"
    location.PostalCode      = "78510"
    location.BillToZipCode   = "78510"
    location.create()

my code doesn't work 

Thanks in advance,

**Comment by MattParr** [comment]
Account entity has ParentAccountID attribute.

**Comment by mcl12345** [comment]
But I talk about "locations" of an account not subsidiary company.

Thanks in advance

**Comment by mcl12345** [comment]
"Locations" here in Autotask :
![capture du 2018-08-16 11-00-47](https://user-images.githubusercontent.com/24854693/44199227-d00a0b00-a143-11e8-8edd-8956b8ac0524.png)
![capture du 2018-08-16 11-00-54](https://user-images.githubusercontent.com/24854693/44199238-d26c6500-a143-11e8-8770-c3396433c44d.png)

**Comment by MattParr** [comment]
AccountPhysicalLocation

**Comment by mcl12345** [comment]
**When I have this :**
   
     account                         = at.new('Account')
     account.AccountName             = 'Test account api python 1'
     account.Phone                   = "0185762128"
     account.AccountType             = at.picklist["Account"]["AccountType"]['Customer']
     account.OwnerResourceID         = 4
     account.Address1                = "une adresse"
     account.BillToAddress1          = "une adresse"
     account.City                    = "une ville"
     account.BillToCity              = "une ville"
     account.PostalCode              = "78510"
     account.BillToZipCode           = "78510"
     account.AccountType             = at.picklist["Account"]["AccountType"]['Customer']
     account.AccountPhysicalLocation = "Test"
     account.set_udf('Services Sophia', 'Services Sophia...')
     account.create()

**I have this error :**
Traceback (most recent call last):
  
File "create_account_simple_example.py", line 29, in <module>
    account.create()

  File "/usr/local/lib/python2.7/dist-packages/atws/monkeypatch/crud.py", line 32, in mp_create
    result = entity._wrapper.create(entity).fetch_one()

  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 242, in fetch_one
    return next(self._generator,None)

  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 318, in process
    for returned_entity in self._send_packet(action, packet, response):

  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 408, in _send_packet
    raise AutotaskProcessException(e,response)

atws.wrapper.AutotaskProcessException: 'During send or receive with the API, an error has \n    occurred.  Please see the exception attribute for details about the error.\n    Please see the response attribute as some API commands may have sucessfully \n    completed before the exception occurred\n    **'TypeNotFound(u"Type not found: 'AccountPhysicalLocation'**",)[]

**Comment by MattParr** [comment]
Create the account.
Then create the account physical locations.  They are both entities.

When you create the account physical location you relate it to the account
using the AccountID field

**Comment by mcl12345** [comment]
This doesn't work, there is no error message ...
436 is the id of the main company

     new_site               = at.new('AccountPhysicalLocation')
     new_site.Name          = "TestSite (site principal)"
     new_site.AccountID     = 436
     new_site.Address1      = "test Address1"
     new_site.City          = "test City"
     new_site.Phone         = "0000000000"
     new_site.PostalCode    = "75001"

**Comment by MattParr** [comment]
Did you call create?

new_multisite.create()

**Comment by mcl12345** [comment]
oh , thanks
I forgot it
