### ISSUE TITLE
Issues with Py3

### ISSUE THREAD

**Issue by tmuncks** [MattParr/python-atws#51]
Hi there,

I'm experiencing some issues, trying to use atws under Python 3.

Installing atws module pulls in suds-jurko 0.6 but it complaints that I should really use 0.7 (which is not available it seems).

Trying to run atws.connect with just username and password, results in an KeyError exception for 'client'. I can specify a client option tn the connect function to bypass that, but I'm not sure what that argument should contain.

I could easily be doing something wrong.

**Comment by MattParr** [comment]
Hi.
The warning is valid.  0.7 is much improved over 0.6... but 0.6 does work fine.
I've been using py3 with this module for a while.  In which version of py3 are you having issues?
Could you include a stack trace and full code example? (please don't forget to obscure username and password)

**Comment by tmuncks** [comment]
Just realized something - Do I need special access, to use the API? That would explain things and might simply require a walk to my AT admins office to fix...

**Comment by MattParr** [comment]
Yes

**Comment by tmuncks** [comment]
Wow - Sorry for wasting your time then!

**Comment by MattParr** [comment]
Also please change your password... I think it might have come in the stack
trace.

It's difficult to detect credential or Auth problems as the endpoint
doesn't respond with XML.  I'll add a generic it's most likely password or
API access warning.

**Comment by tmuncks** [comment]
@MattParr thanks for the heads up on the password thing. The pasted password was actually a random *invalid* password, but I've simply deleted that comment, as I felt it really didn't contribute anything, seeing as it was a different problem all along.

Thanks for a swift reply, though.

**Comment by ChezDaniela** [comment]
I am having the same issues with python 3.7. I pip3 install ed atws , did its requirements, I do have suds v0.7, but it seems due to requirements to use 0.6 (?).
Also when trying to connect it all fails in SAXParseException (xml error). 
Am I doing something wrong?
