### ISSUE TITLE
Updating Existing Ticket Not Working

### ISSUE THREAD

**Issue by DylanWhite2** [MattParr/python-atws#52]
Hi,
Trying to update an existing ticket in AT with the following code.  When running it returns without throwing any errors however the ticket in AT does not update with the new status.  When I run the code with at.update(ticket).execute() or ticket.update() the console throws an error:  _'Conversion from type 'Object' to type 'String' is not valid._ and _Error updating entity for record number[1]_ 

`import logging`
`import atws`
`import atws.monkeypatch.attributes`
`from datetime import datetime`
`import config`

`def main():`
	`at = atws.connect(username='config.user', password='config.password', support_file_path = '/tmp')`
	`query = atws.Query('Ticket')`
	`query.WHERE('id',query.Equals,294562)`
	`ticket = at.query(query).fetch_one()`
	`ticket.Status = at.picklist['Ticket']['Status']['New Alert']`
	`at.update(ticket)`

`if __name__ == '__main__':`
	`main()`

**Comment by MattParr** [comment]
If you print the status value does it show a valid lookup?

Eg
print ticket.Staus

**Comment by DylanWhite2** [comment]
Yes it does print out a valid look up.  I have replied to your other message.  Cheers
