### ISSUE TITLE
Autotask API Version 1.6

### ISSUE THREAD

**Issue by mtingers** [MattParr/python-atws#55]
Hi Matt,

A new API version 1.6 was recently released and I'm opening this issue to get it on your radar (assuming you're still actively maintaining this module).

Please see:
[API Revision History](https://www.autotask.net/help/Content/AdminSetup/2ExtensionsIntegrations/APIs/WSAPI/General_Topics/API%20Revision%20History.htm)

[API 1.6 New Requirements](https://www.autotask.net/help/Content/AdminSetup/2ExtensionsIntegrations/APIs/WSAPI/General_Topics/New_Requirements.htm)

[API 1.6 Docs](https://www.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_6.pdf)

I think the current code will work as-is, but I will be testing in the coming weeks to identify if there are other changes outside of the API user restrictions and SSL/TLS that may break things.

The primary issues will likely revolve around handling the configuration change here:
[AUTOTASK_API_BASE_URL](https://github.com/MattParr/python-atws/blob/3b2a9d67be004b20a03ec2b37ef001d0092e47b2/atws/constants.py#L16)

My initial thoughts on handling this new version (there are probably better ways):

Make the API version selectable in a major release version of this module, but default to the latest 1.6. Deprecate version 1.5 with a warning message. Example:
```python
at = atws.connect(username='..', password='..', api_version='1.5')
## WARNING: AutoTask API version 1.5 is deprecated. Please transition to using the latest 1.6 API.
```

Thanks for you work on this project!

**Comment by MattParr** [comment]
I'll aim to support 1.6 by the end of March.
There is a requirement for two new soap headers and one new connection attribute.
I think I will presume if the new Identifier is supplied then 1.6 else 1.5.
This should mean everything keeps working for 1.5 with no exposed changes.

**Comment by ChezDaniela** [comment]
Great news Matt! Did you get it already tested on 1.6?

**Comment by ryanchausse** [comment]
Hi Matt, thanks for your work on this excellent project. Just taking a brief look at this:

Looks like this will involve overriding a SUDS method to provide the custom SOAP header attribute. Perhaps something to do with suds.sax.attribute and/or suds.sax.element or MessagePlugin? I don't know what the most "elegant" way of adding this to atws would be yet.

Are you close to an update or do you have any strong opinions about how this should be implemented? Maybe I can offer assistance?

**Comment by hoerup** [comment]
For integrationCode header see #57

**Comment by ryanchausse** [comment]
Thanks @hoerup! I've submitted a pull request for v1.6 support based on your contribution.
