### ISSUE TITLE
Just some friendly feedback

### ISSUE THREAD

**Issue by dahifi** [MattParr/python-atws#69]
Hey @MattParr, I just saw this rant (https://github.com/MattParr/python-atws/issues/39) and just wanted to leave you some feedback and thank you for taking the time to write this module. I spent a couple hours recently going over AT's WDSL documentation using the Zeep module the other and I can really appreciate how much work went into getting things were they're at today. Webservices has come a long way since XML's early day, and having even the limited tools to programmatically deal with AT's backend is welcomed. Especially considering the lack of ongoing development for suds and other XML-related modules. 

I've actually been using https://github.com/officecenter/Autotask for the most part, but since Python is my preferred language right now I've been trying to work with this module a bit more in recent days, so I thought I'd take the time to compare the two. 

One thing that I think the PS module handles better is the function generation and query building. They actually use the WDSL definition itself to figure out which entities support which CRUD actions, and dynamically generate the relevant functions and parameters, e.g. get-ticket, update-ticket, delete-ticket, &c..). Additionally, they use a parsing function to build the query XML that is less clunky than what's needed here. 

I realize that we're talking about some metaprogramming, and if I could I would love to contribute, but I think it's way out of my pay-grade as a programmer right now. I need a lot more understanding of how WDSL works and I don't think I have the patience, TBH. 

That said, I think the idea of picklists are perhaps the least user-friendly aspect about using AT's API. It seems very un-Pythonic to have these long picklist strings like `at.picklist['Ticket']['Status'].lookup('Complete')`. I know this isn't your fault, but for me it's one of the most frustrating parts of dealing with AT. 

Thanks again.

**Comment by MattParr** [comment]
Thank you for the link to the powershell wrapper.  It looks great.
Zeep is great... I've used it for an async netsuite integration.

https://atws.readthedocs.io/usage.html#picklists
Lookup is for finding the label assigned to the picklists id.  You should be doing: 
`at.picklist['Ticket']['Status']['Complete']`
Picklists don't seem that long to me.  They are very readable... and easy to use in portable code.

We might have different use cases.  To programmatically build a query using the advanced filter of the powershell wrapper looks difficult.  I also think of queries in SQL so having a query syntax that was readable and programmable was important to me.  

It would be easy to plug in an alternative query syntax.
