### ISSUE TITLE
Move to maintained suds fork now that suds-jurko is no longer maintained

### ISSUE THREAD

**Issue by kti-cameron** [MattParr/python-atws#76]
Since the [suds-jurko](https://bitbucket.org/jurko/suds/src/default/) library that this project uses is no longer active and its Bitbucket repo is getting shutdown this year has any thought been given to moving to the actively maintained suds fork at https://github.com/suds-community/suds? 

[Bitbucket](https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket) says:
>June 1, 2020: users will not be able to use Mercurial features in Bitbucket or via its API and all Mercurial repositories will be removed.

Thanks for creating/maintaining such a useful library!

**Comment by MattParr** [comment]
Yes.  I have switched to suds-community.  Look for it in the next release.
Thank you for pointing it out.

**Comment by kti-cameron** [comment]
Thanks for the response. I'll keep an eye out for the next release.
