### ISSUE TITLE
Installation problems...

### ISSUE THREAD

**Issue by tmuncks** [MattParr/python-atws#8]
Hi there,

I'm having some problems, getting atws to work...

Doing pip install atws seems to complete just fine, as does pip3 install atws (I prefer python3, if possible). However - Nothing seems to work:

/home/user/.local/bin/create_picklist_module.py
Traceback (most recent call last):
  File "/home/user/.local/bin/create_picklist_module.py", line 2, in <module>
    import atws
  File "/home/user/.local/lib/python3.5/site-packages/atws/**init**.py", line 2, in <module>
    from wrapper import connect
ImportError: No module named 'wrapper'

The files seem to be here alright:

.local/lib/python3.5/site-packages/atws
.local/lib/python3.5/site-packages/atws/monkeypatch
.local/lib/python3.5/site-packages/atws/monkeypatch/**pycache**
.local/lib/python3.5/site-packages/atws/monkeypatch/**pycache**/attributes.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/monkeypatch/**pycache**/duckpunch.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/monkeypatch/**pycache**/**init**.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/monkeypatch/**pycache**/crud.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/monkeypatch/**pycache**/userdefinedfields.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/monkeypatch/crud.py
.local/lib/python3.5/site-packages/atws/monkeypatch/**init**.py
.local/lib/python3.5/site-packages/atws/monkeypatch/duckpunch.py
.local/lib/python3.5/site-packages/atws/monkeypatch/userdefinedfields.py
.local/lib/python3.5/site-packages/atws/monkeypatch/attributes.py
.local/lib/python3.5/site-packages/atws/helpers.py
.local/lib/python3.5/site-packages/atws/**pycache**
.local/lib/python3.5/site-packages/atws/**pycache**/connection.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/**pycache**/helpers.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/**pycache**/**init**.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/**pycache**/query.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/**pycache**/picklist.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/**pycache**/constants.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/**pycache**/wrapper.cpython-35.pyc
.local/lib/python3.5/site-packages/atws/query.py
.local/lib/python3.5/site-packages/atws/connection.py
.local/lib/python3.5/site-packages/atws/**init**.py
.local/lib/python3.5/site-packages/atws/picklist.py
.local/lib/python3.5/site-packages/atws/constants.py
.local/lib/python3.5/site-packages/atws/wrapper.py

Am I missing some important step in order to get this working?

**Comment by tmuncks** [comment]
I'm on Ubuntu 15.10 Xenial (alpha), btw:
user@desktop:~$ python -V
Python 2.7.11
user@desktop:~$ python3 -V
Python 3.5.1+

**Comment by tmuncks** [comment]
Geeesh... This is ONLY a problem with Python3, so I'm guessing the module is Python2 only. I'll just do this in Python2, sorry for the disturbance.

**Comment by MattParr** [comment]
Hi,
I have not yet written python3 support in.

**Comment by MattParr** [comment]
@tmuncks This module now supports Python3.

**Comment by tmuncks** [comment]
Awesome, thanks!
