### ISSUE TITLE
Datetime Conversion

### ISSUE THREAD

**Issue by kkawatra09** [MattParr/python-atws#80]
I believe Autotask API is returning all time data in EST or EDT, and the python-atws is converting it to UTC.
I'm not sure if there have been recent changes to the code but seems like the script doesn't respect daylight savings.
For example:
I have a ticket opened on 04/21/2020 12:24 PM(PDT) but after the conversion to UTC I'm getting 2020-04-21 20:24:24 (GMT), where it should be 2020-04-21 19:24:24 (GMT).

**Comment by MattParr** [comment]
This is handled by just a few functions:

https://github.com/MattParr/python-atws/blob/6515a193d88009f97cf61f6bba52730bf594aaa4/atws/constants.py#L9-L15
https://github.com/MattParr/python-atws/blob/6515a193d88009f97cf61f6bba52730bf594aaa4/atws/helpers.py#L154-L174

I don't know if anything has changed on the Autotask side.
I should have made the wrapper default to UTC and allow setting a local time zone if desired.
However I didn't.
The conversion is correct.  My tracing of these times in a world gantt view looks like what you have said is happening.
PDT 1224 -> EST 1424 -> London 2024
Why do you think it should come out an hour earlier?

**Comment by kkawatra09** [comment]
You are right, the conversion is correct. I just thought you were converting to UTC, now I know its LOCAL_TZ='Europe/London'. Thanks for the update.
