### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by dahifi** [MattParr/python-atws#81]
Matt, they just released a REST module. Goodbye suds, goodbye SOAP!

https://www.reddit.com/r/msp/comments/h7ipu2/automating_with_powershell_autotask_psa_rest_api/

**Comment by MattParr** [comment]
That is great news.  We've been off autotask for 2 years and maintaining this was going to become very difficult.

**Comment by VCJames** [comment]
Appreciate the efforts in keeping this running. I admit, I actually started a rewrite to add impersonation support and static typing (parsing the WSDL to generate the library; eliminating init parsing for speed when used with serverless MS Teams add-ons).

I just did a quick and dirty benchmark of the REST vs SOAP APIs (accounts with 2 simple filters). Typically SOAP was 700ish ms; then after 2 consecutive requests, ~400ish ms. The REST API behaved the same but had a 100ms performance hit.

Reviewing the documentation, a good chunk of things are different regarding entities. Such as account being presented as "companies."

How does everyone feel regarding keeping a REST API implementation 1:1 with Autotask?
edit: as in, no runtime parsing of swagger; upstream being fully static.

**Comment by VCJames** [comment]
I'll be continuing with above. For the time being it will be another project entirely, as I can't really see practicality of mixing the two APIs into one library. And I'm not sure the semantics will be compatible.

![image](https://user-images.githubusercontent.com/15795500/86285171-235b9a00-bbb2-11ea-941e-f22076eb427f.png)

![image](https://user-images.githubusercontent.com/15795500/86285197-2a82a800-bbb2-11ea-9cd8-6a16ceb58385.png)

![image](https://user-images.githubusercontent.com/15795500/86285008-e1325880-bbb1-11ea-85d6-057bdbb2c375.png)

... And to be frank I am not skilled enough to make much sense of the methods found in this library. That being said, I'd love to add impersonation support to python-atws for 1.6 parity, just not sure where to start.
